### ISSUE TITLE
Questions list height should auto-detect window height

### ISSUE THREAD

**Issue by KingSupernova31** [KingSupernova31/RulesGuru#89]
On devices with small screens, the question list can run off the bottom of the page like [this](https://user-images.githubusercontent.com/27539004/118725728-54f74700-b7fe-11eb-86f6-86a36c6c9353.png). It should be detecting the screen height and resizing the textarea to match.

**Comment by bwyard** [comment]
#108 pull request should fix this

**Comment by KingSupernova31** [comment]
This looks pretty good, but it's not quite fixed. A scrollbar still shows up on some screen sizes, such as [here](https://user-images.githubusercontent.com/27539004/127790102-dd1ce8a7-0fa5-4177-b7f6-7bc5f9898c69.JPG) and [here](https://user-images.githubusercontent.com/27539004/127790108-74a91ad4-0c12-4871-8aa8-c7c65ddda795.png).

**Comment by bwyard** [comment]
can you provide me the details fo what device and browser is being used for the 2nd photo. as for the first my fix only took into consideration the  question area. ill dig more into once i get some more details from you

**Comment by KingSupernova31** [comment]
Motorola G 2015, 1280x720 HD display, Android 7.1.1, Chrome version 92.0.4515.105

I also just tested on a different phone and it's happening there as well.

**Comment by bwyard** [comment]
i wonder if its the question list within question area causing it

**Comment by KingSupernova31** [comment]
Was the same underlying issue as #186.
